-- IROKO PLATFORM - MASTER SCHEMA
-- Generated by Trae AI for Vercel + Supabase Deployment
-- Date: 2026-01-05

-- =====================================================================================
-- SECTION 1: EXTENSIONS & CORE TABLES
-- =====================================================================================

create extension if not exists "uuid-ossp";

-- 1. USERS (Extends auth.users logic)
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('parent', 'child', 'admin')),
  quiet_hours_start time,
  quiet_hours_end time,
  location_mode text CHECK (location_mode IN ('home', 'diaspora')),
  cultural_group text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.users enable row level security;

-- 2. CHILDREN
create table if not exists public.children (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.users(id) on delete cascade, -- Optional link if child has login
    name text not null,
    dob date,
    age_band text, -- e.g. '7-12'
    avatar_url text,
    current_level text default 'Novice',
    
    -- Gamification Scores
    grit_points int DEFAULT 0,
    omoluabi_points int DEFAULT 0,
    grit_score int DEFAULT 0, -- Legacy alias
    omoluabi_score int DEFAULT 0, -- Legacy alias
    xp_total int DEFAULT 0,
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.children enable row level security;

-- 3. PARENT_CHILD_MAP
create table if not exists public.parent_child_map (
    id uuid default uuid_generate_v4() primary key,
    parent_id uuid references public.users(id) on delete cascade,
    child_id uuid references public.children(id) on delete cascade,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(parent_id, child_id)
);
alter table public.parent_child_map enable row level security;

-- =====================================================================================
-- SECTION 2: MONETIZATION & SUBSCRIPTIONS
-- =====================================================================================

-- 4. PLANS
create table if not exists public.plans (
    id text primary key, -- 'free', 'standard', 'premium'
    name text not null,
    price_monthly numeric,
    price_yearly numeric,
    currency text default 'USD',
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.plans enable row level security;

-- 5. PLAN FEATURES
create table if not exists public.plan_features (
    id uuid default uuid_generate_v4() primary key,
    plan_id text references public.plans(id) on delete cascade,
    feature_key text not null,
    feature_value_type text check (feature_value_type in ('boolean', 'integer', 'text')),
    bool_value boolean,
    int_value integer,
    text_value text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(plan_id, feature_key)
);
alter table public.plan_features enable row level security;

-- 6. SUBSCRIPTIONS
create table if not exists public.subscriptions (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.users(id) not null,
    status text check (status in ('active', 'inactive', 'past_due', 'canceled')),
    plan_id text references public.plans(id),
    current_period_end timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.subscriptions enable row level security;

-- 7. PAYMENTS CONFIG
create table if not exists public.payments_config (
  id uuid default uuid_generate_v4() primary key,
  region text check (region in ('home','diaspora')) not null,
  provider text check (provider in ('paystack','stripe')) not null,
  enabled boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(region)
);
alter table public.payments_config enable row level security;

-- =====================================================================================
-- SECTION 3: VILLAGE CONTENT (MISSIONS, TASKS, GUIDANCE)
-- =====================================================================================

-- 8. MISSION TEMPLATES (The library of missions)
create table if not exists public.mission_templates (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text not null,
  age_min int,
  age_max int,
  category text check (category in ('thinking','money','social','discipline')) not null,
  difficulty text check (difficulty in ('easy','moderate','challenging')) not null,
  requires_parent_review boolean default true,
  active boolean default true,
  culture_tags text[],
  environment_tags text[],
  value_weights jsonb,
  risk_level text check (risk_level in ('low','medium','high')),
  language_mode text check (language_mode in ('english','bilingual','native_first')),
  age_band text, -- e.g. '[6,9)'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.mission_templates enable row level security;

-- 9. TASKS (Daily/Custom tasks)
create table if not exists public.tasks (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  parent_id uuid references public.users(id) on delete cascade,
  name text not null,
  category text check (category in ('discipline','learning','creativity','responsibility','money')) not null,
  start_time timestamp with time zone,
  duration_min int,
  repeat_rule text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.tasks enable row level security;

-- 10. DAILY GUIDANCE (AI generated)
create table if not exists public.daily_guidance (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  guidance_text text,
  content jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.daily_guidance enable row level security;

-- 11. VILLAGE CONTEXT (Cultural Profile)
create table if not exists public.village_context (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade unique not null,
  origin_country text,
  origin_state text,
  origin_town text,
  tribe text,
  environment_type text check (environment_type in ('rural','semi_urban','urban','diaspora')),
  primary_language text,
  secondary_languages text[],
  value_priorities jsonb not null default '{}'::jsonb,
  risk_exposure jsonb not null default '{}'::jsonb,
  learning_bias jsonb not null default '{}'::jsonb,
  ai_persona_hint text,
  is_locked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.village_context enable row level security;

-- =====================================================================================
-- SECTION 4: PROGRESS & LOGS
-- =====================================================================================

-- 12. CHILD MISSIONS (Assigned missions)
create table if not exists public.child_missions (
  id uuid default uuid_generate_v4() primary key,
  mission_template_id uuid references public.mission_templates(id) on delete restrict,
  child_id uuid references public.children(id) on delete cascade,
  parent_id uuid references public.users(id) on delete cascade,
  assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status text check (status in ('assigned','in_progress','completed','reviewed')) default 'assigned',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.child_missions enable row level security;

-- 13. MISSION ATTEMPTS (Execution of a mission)
create table if not exists public.mission_attempts (
  id uuid default uuid_generate_v4() primary key,
  child_mission_id uuid references public.child_missions(id) on delete cascade,
  child_id uuid references public.children(id) on delete cascade,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  choice_data jsonb,
  notes text,
  requires_followup boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.mission_attempts enable row level security;

-- 14. TASK COMPLETIONS
create table if not exists public.task_completions (
  id uuid default uuid_generate_v4() primary key,
  task_id uuid references public.tasks(id) on delete cascade,
  child_id uuid references public.children(id) on delete cascade,
  status text check (status in ('completed','approved')) default 'completed',
  proof_url text,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  verified_at timestamp with time zone
);
alter table public.task_completions enable row level security;

-- 15. BEHAVIOR LOGS
create table if not exists public.behavior_logs (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  type text check (type in ('positive','negative','alert','info')) not null,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.behavior_logs enable row level security;

-- 16. PROGRESS LOGS (Unified log table used by repository.ts)
create table if not exists public.progress_logs (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  mission_id uuid references public.mission_templates(id), -- Or generic mission ID
  status text,
  proof_url text,
  parent_verified boolean default false,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.progress_logs enable row level security;

-- =====================================================================================
-- SECTION 5: REWARDS & GAMIFICATION
-- =====================================================================================

-- 17. REWARDS WALLET
create table if not exists public.rewards_wallet (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  parent_id uuid references public.users(id) on delete cascade,
  points_balance int default 0,
  saved_balance numeric default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.rewards_wallet enable row level security;

-- 18. REWARD CATALOG (Items parents create)
create table if not exists public.rewards (
    id uuid default uuid_generate_v4() primary key,
    parent_id uuid references public.users(id) on delete cascade,
    title text not null,
    cost int,
    emoji text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.rewards enable row level security;

-- 19. REWARD TRANSACTIONS
create table if not exists public.reward_transactions (
  id uuid default uuid_generate_v4() primary key,
  wallet_id uuid references public.rewards_wallet(id) on delete cascade,
  child_id uuid references public.children(id) on delete cascade,
  parent_id uuid references public.users(id) on delete cascade,
  type text check (type in ('earn','spend','adjust')) not null,
  amount_points int default 0,
  amount_currency numeric default 0,
  source text check (source in ('task_completion','parent_award','admin_adjustment','spend_request')),
  status text check (status in ('pending','approved','rejected')) default 'pending',
  proof_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  approved_at timestamp with time zone,
  approved_by uuid references public.users(id)
);
alter table public.reward_transactions enable row level security;

-- =====================================================================================
-- SECTION 6: SYSTEM & ADMIN
-- =====================================================================================

-- 20. SYSTEM UPDATES (Marketing)
CREATE TABLE IF NOT EXISTS public.system_updates (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    title text NOT NULL,
    content text NOT NULL,
    target_audience text CHECK (target_audience IN ('all', 'parent', 'child')) DEFAULT 'all',
    image_url text,
    is_published boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.system_updates ENABLE ROW LEVEL SECURITY;

-- 21. CHILD SESSIONS (Device Management)
create table if not exists public.child_sessions (
  id uuid default uuid_generate_v4() primary key,
  child_id uuid references public.children(id) on delete cascade,
  device_id text not null,
  session_start timestamp with time zone default timezone('utc'::text, now()) not null,
  session_end timestamp with time zone,
  is_active boolean default true,
  revoked boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.child_sessions enable row level security;

-- =====================================================================================
-- SECTION 7: CORE POLICIES (Simplified for Setup)
-- =====================================================================================

-- Allow Public Read on Plans
create policy "Public Plans" on public.plans for select using (true);
create policy "Public Features" on public.plan_features for select using (true);

-- Users
create policy "Users own data" on public.users for all using (auth.uid() = id);

-- Children & Maps
create policy "Parent view children" on public.children for select using (
  exists (select 1 from public.parent_child_map where child_id = children.id and parent_id = auth.uid())
);

-- =====================================================================================
-- SECTION 8: SEED DATA
-- =====================================================================================

-- Seed Plans
insert into public.plans (id, name, price_monthly, price_yearly) values
('free', 'Free', 0, 0),
('standard', 'Standard', 9.99, 99.99),
('premium', 'Premium', 19.99, 199.99)
on conflict (id) do nothing;

-- Seed Features
insert into public.plan_features (plan_id, feature_key, feature_value_type, bool_value, int_value) values
('free', 'ai_coaching', 'boolean', false, null),
('standard', 'ai_coaching', 'boolean', true, null),
('premium', 'ai_coaching', 'boolean', true, null)
on conflict (plan_id, feature_key) do nothing;

-- Seed Payment Config
insert into public.payments_config (region, provider, enabled) values
('home','paystack', false),
('diaspora','stripe', false)
on conflict (region) do nothing;

-- Seed Mission Templates (Sample)
insert into public.mission_templates (title, description, age_min, age_max, category, difficulty, requires_parent_review, active, culture_tags, environment_tags, value_weights, risk_level, language_mode, age_band) values
('Morning Respect Ritual','Greet elders properly at home before starting the day.',6,9,'discipline','easy',true,true,ARRAY['yoruba','igbo','hausa','urhobo'],ARRAY['rural','semi_urban'],'{"respect":5,"family":4}','low','native_first','[6,9)'),
('Personal Space Order','Arrange your sleeping area and explain why order matters.',6,9,'discipline','easy',true,true,ARRAY[]::text[],ARRAY['urban','diaspora'],'{"discipline":4,"independence":3}','low','english','[6,9)'),
('Time Awareness','Prepare for school or activity on time without reminders.',9,13,'discipline','moderate',true,true,ARRAY[]::text[],ARRAY['urban','diaspora'],'{"discipline":4,"responsibility":4}','low','english','[9,13)');
